---
ID: "68fd9178-e925-45ac-aab4-e4a7bfe727a7"
Parent: "ccab8940-57f3-4671-9c3a-261d1c0bfaaa"
Template: "ccab8940-57f3-4671-9c3a-261d1c0bfaaa"
Path: /sitecore/templates/Project/Commercial Tenants/SafariZoo/ContentTypes/BasicPanel/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190220T175728Z
    - ID: "4a43aca4-655b-4296-bc52-08f9ab4cc6cf"
      Hint: HeadingType
      Value: "panel-success"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "e84e212e-f543-4034-9b06-6820899e7232"
      Hint: ContentType
      Value: "panel-success"
